FROM openjdk:18-jdk-alpine
MAINTAINER sabancihan.com
COPY target/notification-service-1.0-SNAPSHOT.jar notification-service-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/notification-service-1.0-SNAPSHOT.jar"]