FROM openjdk:18-jdk-alpine
MAINTAINER sabancihan.com
COPY target/management-service-1.0-SNAPSHOT.jar management-service-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/management-service-1.0-SNAPSHOT.jar"]