FROM openjdk:18-jdk-alpine
MAINTAINER sabancihan.com
COPY target/collection-service-1.0-SNAPSHOT.jar collection-service-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/collection-service-1.0-SNAPSHOT.jar"]