FROM osixia/openldap
LABEL maintainer="erhanb12331@sabanciuniv.edu"
ENV LDAP_ORGANISATION="Sabanci Han"
ENV LDAP_DOMAIN="sabancihan.com"
COPY bootstrap.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

