version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: management
    ports:
      - "5432:5432"

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    container_name: api-gateway
    restart: always
    environment:
      - ENVIRONMENT_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    container_name: discovery-server
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT_HOST=host.docker.internal

  detection-service:
    build: ./detection-service
    container_name: detection-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT_HOST=host.docker.internal
      - KAFKA_HOST=broker
      - KAFKA_PORT=29092

  management-service:
    build: ./management-service
    container_name: management-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT_HOST=host.docker.internal
      - KAFKA_HOST=broker
      - KAFKA_PORT=29092

  collection-service:
    build: ./collection-service
    container_name: collection-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT_HOST=host.docker.internal
      - KAFKA_HOST=broker
      - KAFKA_PORT=29092

  register-service:
    build: ./register-service
    container_name: register-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT_HOST=host.docker.internal

  notification-service:
    build: ./notification-service
    container_name: notification-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT_HOST=host.docker.internal
      - KAFKA_HOST=broker
      - KAFKA_PORT=29092



